export const syllabusMock = [
  {
    id: 1,
    name: "CBSE",
    description: "Central Board of Secondary Education",
  },
  {
    id: 2,
    name: "ICSE",
    description: "Indian Certificate of Secondary Education",
  },
  {
    id: 3,
    name: "SSC or State Board",
    description: "Secondary School Certificate",
  },
];

export const classMock = [
  {
    id: 1,
    clas: "class 1",
    syllabus: "CBSE",
  },
  {
    id: 2,
    clas: "class 2",
    syllabus: "CBSE",
  },
  {
    id: 3,
    clas: "class 3",
    syllabus: "CBSE",
  },
  {
    id: 4,
    clas: "class 4",
    syllabus: "CBSE",
  },
  {
    id: 5,
    clas: "class 5",
    syllabus: "CBSE",
  },
  {
    id: 6,
    clas: "class 6",
    syllabus: "CBSE",
  },
  {
    id: 7,
    clas: "class 7",
    syllabus: "CBSE",
  },
  {
    id: 8,
    clas: "class 8",
    syllabus: "CBSE",
  },
  {
    id: 9,
    clas: "class 9",
    syllabus: "CBSE",
  },
];

export const SubjMock = [
  {
    id: 2,
    subject: "English",
    clas_hive: "class 2",
    syllabus: "CBSE",
  },
  {
    id: 29,
    subject: "Kannada",
    clas_hive: "class 2",
    syllabus: "CBSE",
  },
  {
    id: 56,
    subject: "Math",
    clas_hive: "class 2",
    syllabus: "CBSE",
  },
  {
    id: 83,
    subject: "Science",
    clas_hive: "class 2",
    syllabus: "CBSE",
  },
  {
    id: 109,
    subject: "Social",
    clas_hive: "class 2",
    syllabus: "CBSE",
  },
];

export const TopicMock = [
  {
    id: 17,
    name: "youtube-g1203e8c69_640.png",
    subject: "Social",
    clas_hive: "class 1",
    syllabus: "CBSE",
    url: "/media/youtube-g1203e8c69_640_utQX2Ix.png",
    filetype: "image/png",
    tags: ["math1", "abc", "asdf"],
    filefield: "/media/youtube-g1203e8c69_640_utQX2Ix.png",
  },
  {
    id: 18,
    name: "Read Me.txt",
    subject: "Social",
    clas_hive: "class 1",
    syllabus: "CBSE",
    url: "/media/Read_Me.txt",
    filetype: "text/plain",
    tags: ["math", "abc", "asdf"],
    filefield: "/media/Read_Me.txt",
  },
  {
    id: 19,
    name: "Read Me.txt",
    subject: "Social",
    clas_hive: "class 1",
    syllabus: "CBSE",
    url: "/media/Read_Me_b5IsCn1.txt",
    filetype: "text/plain",
    tags: ["math", "abc", "asdf"],
    filefield: "/media/Read_Me_b5IsCn1.txt",
  },
  {
    id: 20,
    name: "selection.json",
    subject: "Social",
    clas_hive: "class 1",
    syllabus: "CBSE",
    url: "/media/selection.json",
    filetype: "application/json",
    tags: ["math", "abc", "asdf"],
    filefield: "/media/selection.json",
  },
  {
    id: 21,
    name: "style.css",
    subject: "Social",
    clas_hive: "class 1",
    syllabus: "CBSE",
    url: "/media/style.css",
    filetype: "text/css",
    tags: ["math", "abc", "asdf"],
    filefield: "/media/style.css",
  },
];

export const searchListMock = [
  {
    id: 1,
    name: "logo",
    subject: "English",
    clas_hive: "class 8",
    syllabus: "ICSE",
    url: "/media/ajaxlogo.svg",
    filetype: "image/svg+xml",
    tags: ["crazy", "encore", "logo", "ajax", "math"],
    filefield: "/media/ajaxlogo.svg",
  },
  {
    id: 2,
    name: "logo",
    subject: "English",
    clas_hive: "class 8",
    syllabus: "ICSE",
    url: "/media/ajaxlogo_5CPr8yE.svg",
    filetype: "image/svg+xml",
    tags: ["crazy", "encore", "logo", "ajax", "math"],
    filefield: "/media/ajaxlogo_5CPr8yE.svg",
  },
  {
    id: 3,
    name: "logo",
    subject: "English",
    clas_hive: "class 8",
    syllabus: "ICSE",
    url: "/media/ajaxlogo_o4FOKiV.svg",
    filetype: "image/svg+xml",
    tags: ["crazy", "encore", "logo", "ajax", "math"],
    filefield: "/media/ajaxlogo_o4FOKiV.svg",
  },
  {
    id: 4,
    name: "test",
    subject: "English",
    clas_hive: "class 8",
    syllabus: "ICSE",
    url: "/media/_static_media_test.d3aa49eba425aace207c.pdf",
    filetype: "application/pdf",
    tags: ["math", "abc", "asdf"],
    filefield: "/media/_static_media_test.d3aa49eba425aace207c.pdf",
  },
  {
    id: 5,
    name: "test",
    subject: "English",
    clas_hive: "class 8",
    syllabus: "ICSE",
    url: "/media/_static_media_test.d3aa49eba425aace207c_mCxuwMP.pdf",
    filetype: "application/pdf",
    tags: ["math", "abc", "asdf"],
    filefield: "/media/_static_media_test.d3aa49eba425aace207c_mCxuwMP.pdf",
  },
  {
    id: 6,
    name: "test",
    subject: "English",
    clas_hive: "class 8",
    syllabus: "ICSE",
    url: "/media/_static_media_test.d3aa49eba425aace207c_NA8NOnO.pdf",
    filetype: "application/pdf",
    tags: ["math", "abc", "asdf"],
    filefield: "/media/_static_media_test.d3aa49eba425aace207c_NA8NOnO.pdf",
  },
  {
    id: 7,
    name: "test",
    subject: "English",
    clas_hive: "class 8",
    syllabus: "ICSE",
    url: "/media/_static_media_test.d3aa49eba425aace207c_CFk2yzz.pdf",
    filetype: "application/pdf",
    tags: ["math", "abc", "asdf"],
    filefield: "/media/_static_media_test.d3aa49eba425aace207c_CFk2yzz.pdf",
  },
  {
    id: 8,
    name: "test",
    subject: "English",
    clas_hive: "class 8",
    syllabus: "ICSE",
    url: "/media/pexels-vie-studio-4439444.jpg",
    filetype: "image/jpeg",
    tags: ["math", "abc", "asdf"],
    filefield: "/media/pexels-vie-studio-4439444.jpg",
  },
  {
    id: 9,
    name: "test",
    subject: "English",
    clas_hive: "class 8",
    syllabus: "ICSE",
    url: "/media/pexels-vie-studio-4439444_nlaXaiz.jpg",
    filetype: "image/jpeg",
    tags: ["math", "abc", "asdf"],
    filefield: "/media/pexels-vie-studio-4439444_nlaXaiz.jpg",
  },
  {
    id: 10,
    name: "youtube-g1203e8c69_640.png",
    subject: "English",
    clas_hive: "class 8",
    syllabus: "ICSE",
    url: "/media/youtube-g1203e8c69_640.png",
    filetype: "image/png",
    tags: ["math", "abc", "asdf"],
    filefield: "/media/youtube-g1203e8c69_640.png",
  },
  {
    id: 11,
    name: "_static_media_test.d3aa49eba425aace207c.pdf",
    subject: "English",
    clas_hive: "class 8",
    syllabus: "ICSE",
    url: "/media/_static_media_test.d3aa49eba425aace207c_Cdah5FC.pdf",
    filetype: "application/pdf",
    tags: ["math", "abc", "asdf"],
    filefield: "/media/_static_media_test.d3aa49eba425aace207c_Cdah5FC.pdf",
  },
  {
    id: 12,
    name: "PowerShell-7.2.5-win-x64.msi",
    subject: "English",
    clas_hive: "class 8",
    syllabus: "ICSE",
    url: "/media/PowerShell-7.2.5-win-x64.msi",
    filetype: "application/octet-stream",
    tags: ["math", "abc", "asdf"],
    filefield: "/media/PowerShell-7.2.5-win-x64.msi",
  },
  {
    id: 13,
    name: "Miniconda3-latest-Windows-x86_64.exe",
    subject: "English",
    clas_hive: "class 8",
    syllabus: "ICSE",
    url: "/media/Miniconda3-latest-Windows-x86_64.exe",
    filetype: "application/x-msdownload",
    tags: ["math", "abc", "asdf"],
    filefield: "/media/Miniconda3-latest-Windows-x86_64.exe",
  },
  {
    id: 14,
    name: "_static_media_test.d3aa49eba425aace207c.pdf",
    subject: "English",
    clas_hive: "class 8",
    syllabus: "ICSE",
    url: "/media/_static_media_test.d3aa49eba425aace207c_shX9V2Q.pdf",
    filetype: "application/pdf",
    tags: ["math", "abc", "asdf"],
    filefield: "/media/_static_media_test.d3aa49eba425aace207c_shX9V2Q.pdf",
  },
  {
    id: 15,
    name: "_static_media_test.d3aa49eba425aace207c.pdf",
    subject: "English",
    clas_hive: "class 1",
    syllabus: "CBSE",
    url: "/media/_static_media_test.d3aa49eba425aace207c_AB1j4RP.pdf",
    filetype: "application/pdf",
    tags: ["math", "abc", "asdf"],
    filefield: "/media/_static_media_test.d3aa49eba425aace207c_AB1j4RP.pdf",
  },
  {
    id: 16,
    name: "youtube-g1203e8c69_640.png",
    subject: "Kannada",
    clas_hive: "class 1",
    syllabus: "CBSE",
    url: "/media/youtube-g1203e8c69_640_wjf7iwL.png",
    filetype: "image/png",
    tags: ["math", "abc", "asdf"],
    filefield: "/media/youtube-g1203e8c69_640_wjf7iwL.png",
  },
  {
    id: 17,
    name: "youtube-g1203e8c69_640.png",
    subject: "Social",
    clas_hive: "class 1",
    syllabus: "CBSE",
    url: "/media/youtube-g1203e8c69_640_utQX2Ix.png",
    filetype: "image/png",
    tags: ["math", "abc", "asdf"],
    filefield: "/media/youtube-g1203e8c69_640_utQX2Ix.png",
  },
  {
    id: 18,
    name: "Read Me.txt",
    subject: "Social",
    clas_hive: "class 1",
    syllabus: "CBSE",
    url: "/media/Read_Me.txt",
    filetype: "text/plain",
    tags: ["math", "abc", "asdf"],
    filefield: "/media/Read_Me.txt",
  },
  {
    id: 19,
    name: "Read Me.txt",
    subject: "Social",
    clas_hive: "class 1",
    syllabus: "CBSE",
    url: "/media/Read_Me_b5IsCn1.txt",
    filetype: "text/plain",
    tags: ["math", "abc", "asdf"],
    filefield: "/media/Read_Me_b5IsCn1.txt",
  },
  {
    id: 20,
    name: "selection.json",
    subject: "Social",
    clas_hive: "class 1",
    syllabus: "CBSE",
    url: "/media/selection.json",
    filetype: "application/json",
    tags: ["math", "abc", "asdf"],
    filefield: "/media/selection.json",
  },
  {
    id: 21,
    name: "style.css",
    subject: "Social",
    clas_hive: "class 1",
    syllabus: "CBSE",
    url: "/media/style.css",
    filetype: "text/css",
    tags: ["math", "abc", "asdf"],
    filefield: "/media/style.css",
  },
];
